# platform :ios, '9.0'

target 'chatApplication' do
  use_frameworks!

  # Pods for chatApplication
  
  pod 'CLTypingLabel'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'IQKeyboardManagerSwift'
  
end
